name = "GenomicVectors"
uuid = "96124ad7-5c0a-5c8f-8316-419835a3cefd"
version = "0.4.1"

[deps]
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
RLEVectors = "17b45ede-fd0d-54ef-b825-8cf9fc64da95"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
BioAlignments = ">= 0.1.0"
GenomicFeatures = ">= 1.0.0"
julia = "1"
